export const tips = [
    "Do your best to get your footage in the morning or evening, when the light is softer.",
    "Plan your video first.",
    "The location of your video matters. Consider what the location tells your audience.",
    "As a general rule, you should shoot your video using soft lighting, rather than hard lighting.",
    "Audiences are easily distracted by objects in the background, keep the backdrop super simple.",
    "Steer clear of shaky footage.",
    "Use the rule of thirds.",
    "Stick to a time limit, the average attention span is 8.52 seconds.",
    "Focus on the audio quality, eliminate any background noise.",
    "Capture several angles, shoot your subject from a variety of different angles.",
    "Keep your editing simple, the best course of action is to keep your editing style slick, smooth, and simple.",
    "Don’t rely on the equipment — you need technique too.",
    "Don’t forget to check the sound quality.",
    "Don’t make your professional videos too long.",
    "Don’t rush into making your video without a plan.",
    "Avoid flashy effects and garish transitions, this can detract from the content of the video.",
    "Make sure that you plan ahead, get the right equipment, and take things slowly.",
    "To ensure that your professional video is interesting, pick out two or three central points.",
    "Use plenty of light, it makes a huge difference in the quality of a finished professional video.",
    "Use a clean background, nothing looks less professional than a messy or distracting background.",
    "Keep your editing simple.",
    "Prioritize crisp, clear audio.",
    "Avoid shaky footage.",
    "Understand the rule of thirds.",
    "Plan your videos in advance.",
    "Promote your videos.",
    "Invest time in writing a winning script.",
    "Deliver confident narration in front of the camera.",
    "Pay attention to pacing when editing.",
    "Review your video for clarity and brevity.",
    "Research your topic, the easiest ways to decide your video topic is to conduct keyword research inside YouTube.",
    "Pick the right location, you can shoot the video in-house or head outdoors.",
    "For beginners, natural light is an excellent option. It doesn’t cost anything and is fully capable of making the subject of your video look good.",
    "As you scale your production capacity, you’ll probably want to invest in lighting equipment to boost the quality of your videos.",
    "Stabilized footage is essential for the success, shaky footage looks unprofessional and strains the eyes of your audience.",
    "Composition is how you choose to frame your subject in the video you’re about to capture.",
    "Be comfortable on camera, we suggest you sit/stand up straight with your shoulders back so you look professional, focused and relaxed.",
    "Try to speak slowly and enunciate each word clearly so your message is easy to understand.",
    "Filming videos in small segments is a great way to keep yourself focused on the topic you’re discussing. And it also becomes easier to edit the footage in post-production.",
    "Regardless of the type of video you create, whether educational, business-related or simply an artistic video, make sure you properly share it with your audience to maximize its impact.",
    "You can also share your videos on different groups and forums, such as Reddit, Quora and Facebook groups.",
    "Creating professional videos sounds intimidating, but it doesn’t really have to be.",
    "Video production is the process used to produce video content. Typically, it consists of three phases: pre-production, production, and post-production.",
    "Professional-quality video production requires a lot of specialized cameras, lighting, audio.",
    "Writing a script is always necessary if your video includes a professional voice-over or people talking to the camera.",
    "Narrow down the focus of your marketing videos to just one topic, message, or idea.",
    "If you’re going for a live-action piece, scout and secure the locations you have in mind for the video shoot ahead of time.",
    "Make a checklist of the gear you’re going to need before you go to the video shoot location: tripods, cords, spare batteries.",
    "Whether you’re going for live-action or animated marketing videos, you can incorporate your brand’s characteristic colors to increase brand awareness and recognition.",
    "Once you’re done filming the raw, unedited footage, immediately upload it to a hard drive or cloud storage service to prevent losing it or deleting it on accident.",
    "Most video editing software allows you to clip the beginnings and ends of footage as you import it, so try to delete any false starts or pauses to save time.",
    "If you’re adding an intro and outro, now it’s the time to do so.",
    "Background music and sound effects are a must in marketing video production.",
    "Keep your camera steady to avoid shaky footage.",
    "Use a tripod or stabilizer to achieve smooth camera movements.",
    "Experiment with different camera angles and perspectives to add visual interest to your videos.",
    "Consider the background of your shots and ensure it complements your subject.",
    "Use natural light whenever possible, but be mindful of harsh shadows.",
    "Invest in a good microphone for clear audio.",
    "Use a windscreen or dead cat to reduce wind noise when filming outdoors.",
    "Create a shot list or storyboard to plan your shots in advance.",
    "Shoot in high resolution to maintain quality when editing and exporting.",
    "Experiment with different frame rates to achieve different visual effects.",
    "Consider the pacing of your edits to keep your audience engaged.",
    "Use transitions sparingly and purposefully.",
    "Add captions or subtitles to make your videos accessible to a wider audience.",
    "Use B-roll footage to add context or illustrate key points.",
    "Experiment with different video formats, such as tutorials, vlogs, or interviews.",
    "Collaborate with other creators to reach new audiences and share expertise.",
    "Engage with your audience by responding to comments and messages.",
    "Use analytics to track the performance of your videos and identify areas for improvement.",
    "Stay up to date with trends and changes in the video industry.",
    "Experiment with different editing styles and techniques to develop your own unique style.",
    "Consider the emotional impact of your videos and how you want your audience to feel.",
    "Use storytelling techniques to create a narrative arc and keep viewers hooked.",
    "Consider the length of your videos and tailor them to the platform and audience.",
    "Use music to enhance the mood and tone of your videos.",
    "Experiment with different video effects and filters to add visual interest.",
    "Use color grading to create a consistent look and feel across your videos.",
    "Consider the composition of your shots and how elements are arranged within the frame.",
    "Use foreground elements to add depth and dimension to your shots.",
    "Experiment with different camera movements, such as pans, tilts, and zooms.",
    "Use the 'rule of thirds' to compose visually pleasing shots.",
    "Experiment with different focal lengths to achieve different perspectives.",
    "Use depth of field to draw attention to your subject and create a sense of depth.",
    "Experiment with different aspect ratios to achieve different visual effects.",
    "Use framing to highlight important elements within your shots.",
    "Use leading lines to draw the viewer's eye towards your subject.",
    "Experiment with different lighting setups to achieve different moods and effects.",
    "Use soft lighting to create flattering portraits and reduce harsh shadows.",
    "Experiment with different color temperatures to achieve different effects.",
    "Use natural light to create soft, diffused lighting.",
    "Experiment with different light modifiers, such as reflectors and diffusers, to control the quality and direction of light.",
    "Use backlighting to create depth and separation between your subject and the background.",
    "Use sidelighting to create texture and dimension in your shots.",
    "Use key, fill, and rim lighting to create a balanced and visually appealing lighting setup.",
    "Use practical lights, such as lamps and candles, to add warmth and atmosphere to your shots.",
    "Use artificial lights, such as LED panels and strobes, to create controlled and consistent lighting setups.",
    "Experiment with different lighting ratios to achieve different effects.",
    "Use hard lighting to create dramatic shadows and highlights.",
    "Experiment with different light sources, such as tungsten, fluorescent, and LED lights, to achieve different color temperatures and effects.",
    "Use gels and filters to add color and mood to your lighting setups.",
    "Experiment with different lighting angles and positions to achieve different effects.",
    "Use natural light to create soft, flattering portraits.",
    "Use artificial lights to create controlled and consistent lighting setups.",
    "Use diffusers and reflectors to modify the quality and direction of light.",
    "Use backlighting to create separation between your subject and the background.",
    "Experiment with different light modifiers, such as softboxes and umbrellas, to achieve different lighting effects.",
    "Use practical lights, such as lamps and candles, to add warmth and atmosphere to your shots.",
    "Use artificial lights, such as LED panels and strobes, to create controlled and consistent lighting setups.",
    "Experiment with different lighting ratios to achieve different effects.",
    "Use hard lighting to create dramatic shadows and highlights.",
    "Experiment with different light sources, such as tungsten, fluorescent, and LED lights, to achieve different color temperatures and effects.",
    "Use gels and filters to add color and mood to your lighting setups.",
    "Experiment with different lighting angles and positions to achieve different effects.",
    "Use natural light to create soft, flattering portraits.",
    "Use artificial lights to create controlled and consistent lighting setups.",
    "Use diffusers and reflectors to modify the quality and direction of light.",
    "Use backlighting to create separation between your subject and the background.",
    "Experiment with different light modifiers, such as softboxes and umbrellas, to achieve different lighting effects.",
    "Use practical lights, such as lamps and candles, to add warmth and atmosphere to your shots.",
    "Use artificial lights, such as LED panels and strobes, to create controlled and consistent lighting setups.",
    "Experiment with different lighting ratios to achieve different effects.",
    "Use hard lighting to create dramatic shadows and highlights.",
    "Experiment with different light sources, such as tungsten, fluorescent, and LED lights, to achieve different color temperatures and effects.",
    "Use gels and filters to add color and mood to your lighting setups.",
    "Experiment with different lighting angles and positions to achieve different effects.",
    "Use natural light to create soft, flattering portraits.",
    "Use artificial lights to create controlled and consistent lighting setups.",
    "Use diffusers and reflectors to modify the quality and direction of light.",
    "Use backlighting to create separation between your subject and the background.",
    "Experiment with different light modifiers, such as softboxes and umbrellas, to achieve different lighting effects.",
    "Use practical lights, such as lamps and candles, to add warmth and atmosphere to your shots.",
    "Use artificial lights, such as LED panels and strobes, to create controlled and consistent lighting setups.",
    "Experiment with different lighting ratios to achieve different effects.",
    "Use hard lighting to create dramatic shadows and highlights.",
    "Experiment with different light sources, such as tungsten, fluorescent, and LED lights, to achieve different color temperatures and effects.",
    "Use gels and filters to add color and mood to your lighting setups.",
    "Experiment with different lighting angles and positions to achieve different effects.",
    "Do your best to get your footage in the morning or evening, when the light is softer.",
    "Plan your video first.",
    "The location of your video matters. Consider what the location tells your audience.",
    "As a general rule, you should shoot your video using soft lighting, rather than hard lighting.",
    "Audiences are easily distracted by objects in the background, keep the backdrop super simple.",
    "Steer clear of shaky footage.",
    "Use the rule of thirds.",
    "Stick to a time limit, the average attention span is 8.52 seconds",
  ];